# -*- coding: utf-8 -*-
"""Tugas Akhir - Kualitas Udara Kota Semarang menggunakan RF dan XGBOOST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P31_P1_Smzph2PYfHJ5uIbY-xkXX4czi

### **Pengumpulan Data**

**Memuat Data**
"""

import pandas as pd

#Membaca data dari file CSV
from google.colab import drive

drive.mount('/content/drive')
df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/dataset/DataStasiunSemarangMijen.csv', sep=';')

df.info()

"""### **Exploratory Data Analysis (EDA)**

**Analisis Karakteristik / Informasi Dataset**
"""

df.dtypes

# statistika deskriptif
df.describe()

"""**Memeriksa apakah ada Nilai Null**"""

# pengecekan missing value
print(df.isnull().sum())
# persentase missing value pada setiap variabel
print(df.isnull().sum() / len(df) * 100)

# Menampilkan baris yang duplikat
duplicate_rows = df[df.duplicated()]
print(f"Baris duplikat: {duplicate_rows.shape[0]} baris")

df.nunique()

"""**Konversi ke Format Datetime**"""

df['Waktu'] = pd.to_datetime(df['Waktu'], format='%Y-%m-%d %H:%M:%S')

print(df[['Waktu']].dtypes)

"""**Cek Korelasi antara fitur – fitur atau Atribut Numeric**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Calculate the correlation matrix for numeric columns
# Ensure non-numeric columns are dropped or converted if necessary
correlation_matrix = df.select_dtypes(include=['number']).corr()

# Visualisasi matriks korelasi
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, fmt=".2f",
cmap='coolwarm', linewidths=0.5)
plt.title("Heatmap Korelasi")
plt.show()

"""**Visualisasi Distribusi Data**"""

import matplotlib.pyplot as plt

# Menentukan kolom yang akan divisualisasikan
col = 'CO'

# Membuat figure dan axis tunggal (karena hanya 1 variabel)
plt.figure(figsize=(12,6))

# Membuat diagram garis
plt.plot(df['Waktu'], df[col], label=col)

# Menambahkan judul dan label sumbu
plt.title(f'Diagram Garis {col}')
plt.xlabel('Waktu')
plt.ylabel('Konsentrasi CO (mg/m³)')

# Menambahkan grid
plt.grid(True)

# Menampilkan plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Menentukan kolom
col = 'CO'

# Membuat histogram
plt.figure(figsize=(12,6))
plt.hist(df[col], bins=30)

# Menambahkan judul dan label
plt.title(f'Histogram Distribusi {col}')
plt.xlabel('Konsentrasi CO (mg/m³)')
plt.ylabel('Frekuensi')

# Menambahkan grid
plt.grid(True)

# Menampilkan plot
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Menentukan kolom
col = 'CO'

# Membuat boxplot sederhana dengan warna
df[col].plot(
    kind='box',
    figsize=(10,4),
    vert=False,
    patch_artist=True,
    boxprops=dict(facecolor='steelblue', linewidth=0.5),  # garis box lebih tipis
    medianprops=dict(color='black', linewidth=0.5)
)

# Menambahkan judul dan label
plt.title(f'Boxplot Distribusi {col}')
plt.xlabel('Konsentrasi CO (mg/m³)')

# Grid vertikal saja
plt.grid(True, axis='x')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

cols = ['CO']

fig, axes = plt.subplots(3, 3, figsize=(15,10))
axes = axes.flatten()

for ax, col in zip(axes, cols):
    df.plot(
        x='Waktu',
        y=col,
        ax=ax,
        title=col,
        legend=False,
        grid=True
    )

    # Perbaikan label sumbu
    ax.set_xlabel('Time')
    ax.set_ylabel('CO Concentration (mg/m³)')

for ax in axes[len(cols):]:
    ax.remove()

plt.tight_layout()
plt.show()

"""## **Data Preprocessing**

### **Data Selection**
"""

df_procc = df[['CO']]

"""### **Handling Missing Value**"""

df_procc = df[['CO']]
print("Missing values sebelum perbaikan:")
print(df_procc.isnull().sum())

from sklearn.impute import KNNImputer
import pandas as pd

# Inisialisasi KNN Imputer
imputer = KNNImputer(
    n_neighbors=5,
    weights="distance"   # lebih stabil dibanding uniform
)

# Melakukan imputasi KNN
df_procc_imputed = imputer.fit_transform(df_procc)

# Kembalikan ke DataFrame
df_procc = pd.DataFrame(df_procc_imputed, columns=df_procc.columns)

print("\nJumlah missing values setelah KNN Imputation:")
print(df_procc.isnull().sum())

df_procc.head()

"""### **Inverse Transformation**"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_procc)

df_procc_imputed = imputer.fit_transform(df_scaled)

df_procc = pd.DataFrame(
    scaler.inverse_transform(df_procc_imputed),
    columns=df_procc.columns
)

"""### **Label Encoding**"""

import numpy as np

def calculate_ispu(x, bp_conc, bp_ispu):
    """
    Calculate ISPU using linear interpolation.
    x: actual concentration
    bp_conc: list of concentration breakpoints [B_low, ..., B_high]
    bp_ispu: list of ISPU index breakpoints [I_low, ..., I_high]
    """
    if x <= bp_conc[0]:
        return (bp_ispu[0] / bp_conc[0]) * x if bp_conc[0] != 0 else 0

    for i in range(1, len(bp_conc)):
        if x <= bp_conc[i]:
            Bb = bp_conc[i-1]
            Ba = bp_conc[i]
            Ib = bp_ispu[i-1]
            Ia = bp_ispu[i]
            return ((Ia - Ib) / (Ba - Bb)) * (x - Bb) + Ib

    # If x exceeds the highest breakpoint, extrapolate or cap (usually capped or higher slope)
    return bp_ispu[-1]

# Define Breakpoints based on PERMEN LHK No. 14 Tahun 2020
ispu_indices = [0, 50, 100, 200, 300, 500]
breakpoints = {
    'CO': [0, 4000, 8000, 15000, 30000, 45000],
}

# Calculate individual ISPU for each pollutant
pollutants = [ 'CO']
for p in pollutants:
    df_procc[f'ISPU_{p}'] = df_procc[p].apply(lambda val: calculate_ispu(val, breakpoints[p], ispu_indices))

# Overall ISPU is the maximum value among all pollutants
df_procc['ISPU_Score'] = df_procc[[f'ISPU_{p}' for p in pollutants]].max(axis=1)

# Categorize based on ISPU Score
def get_category(score):
    if score <= 50:
        return 'Baik'
    elif score <= 100:
        return 'Sedang'
    elif score <= 200:
        return 'Tidak Sehat'
    elif score <= 300:
        return 'Sangat Tidak Sehat'
    else:
        return 'Berbahaya'

df_procc['Kategori'] = df_procc['ISPU_Score'].apply(get_category)

# Display the results
print("Distribusi Kategori ISPU:")
print(df_procc['Kategori'].value_counts())
print("\nContoh data dengan Label ISPU:")
df_procc[['CO', 'ISPU_Score', 'Kategori']].head()

from sklearn.preprocessing import LabelEncoder

# 1. Membuat df_procc2 dengan kolom pilihan
cols_to_keep = ['CO', 'ISPU_Score', 'Kategori']
df_procc2 = df_procc[cols_to_keep].copy()

# 2. Buat custom mapping sesuai urutan yang diinginkan
custom_mapping = {
    'Baik': 0,
    'Berbahaya': 1,
    'Sedang': 2,
    'Tidak Sehat': 3,
    'Sangat Tidak Sehat': 4
}

# Terapkan custom mapping ke kolom 'Kategori'
df_procc2['Kategori_Encoded'] = df_procc2['Kategori'].map(custom_mapping)

# 3. Menampilkan mapping kategori
print("Mapping Kategori:", custom_mapping)

# 4. Menampilkan hasil
df_procc2.head()

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Visualisasi distribusi dari hasil Label Encoding
plt.figure(figsize=(10, 6))
sns.countplot(data=df_procc2, x='Kategori_Encoded', palette='magma', hue='Kategori_Encoded', legend=False)
plt.title('Distribusi Kategori Kualitas Udara (Encoded)')
plt.xlabel('Label Numerik (Encoded)')
plt.ylabel('Jumlah Data')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# 2. Menampilkan referensi custom_mapping dari cell sebelumnya untuk memudahkan pembacaan
print("Referensi Mapping Label Encoding:")
# Ensure custom_mapping is available from the previous cell's execution
for label, value in custom_mapping.items():
    print(f"Label {value} = {label}")

"""### **Normalisasi dan Pembagian Dataset**"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer # Import KNNImputer again

# Define features (X) and target (y)
X = df_procc2[['CO']]
y = df_procc2['Kategori_Encoded']

# Initialize and fit StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X) # Scale the imputed data

# Splitting the dataset into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Verify the split by printing the shapes
print(f"\nX_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""### **SMOTE**"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

sns.countplot(x=y_train)  # gunakan label sebelum SMOTE

plt.title('Category Distribution Before SMOTE')
plt.xlabel('ISPU Category')
plt.ylabel('Number of Samples')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

import numpy as np

# Create a copy of X_train
X_train_noisy = X_train.copy()

# Calculate the standard deviation of the 'CO' column from the original X_train DataFrame
# X_train is a numpy array, so access 'CO' by its index (0)
co_std = X_train[:, 0].std()

# Define the noise standard deviation by multiplying co_std by 1.5 (significantly increasing noise)
noise_std = co_std * 1.5

# Generate Gaussian noise
noise = np.random.normal(loc=0, scale=noise_std, size=X_train_noisy.shape)

# Add the generated noise to the 'CO' column of X_train_noisy
# X_train_noisy is a numpy array, so access 'CO' by its index (0)
X_train_noisy[:, 0] = X_train_noisy[:, 0] + noise[:, 0]

print("First 5 rows of original X_train:")
print(X_train[:5])

print("\nFirst 5 rows of X_train_noisy (with added noise): ")
print(X_train_noisy[:5]) # This will now be very close to X_train

print(f"\nStandard deviation of original 'CO' in X_train: {co_std:.4f}")
print(f"Noise standard deviation applied: {noise_std:.4f}")

from sklearn.ensemble import RandomForestClassifier

# Instantiate the Random Forest Classifier with even more restricted parameters
# This is done to intentionally reduce accuracy as per the user's request.
best_rf_model_extremely_low_accuracy = RandomForestClassifier(
    n_estimators=100,         # Further reduced number of trees
    max_depth=2,            # Further reduced maximum depth of trees
    random_state=42,        # For reproducibility
    class_weight='balanced' # Keeping class_weight balanced to still handle imbalance, but overall model is weaker
)

# Train the model using the noisy training data
best_rf_model_extremely_low_accuracy.fit(X_train_noisy, y_train)

print("Random Forest model trained with extremely restricted parameters.")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Create a noisy version of X_test, similar to how X_train_noisy was created
X_test_noisy_higher_noise = X_test.copy()

# Generate Gaussian noise for X_test
noise_test = np.random.normal(loc=0, scale=noise_std, size=X_test_noisy_higher_noise.shape)

# Add the generated noise to the 'CO' column of X_test_noisy_higher_noise
X_test_noisy_higher_noise[:, 0] = X_test_noisy_higher_noise[:, 0] + noise_test[:, 0]

# Make predictions on the *higher noisy* test set using the extremely restricted model
y_pred_higher_noise_extremely_restricted = best_rf_model_extremely_low_accuracy.predict(X_test_noisy_higher_noise)

# Evaluate the model's performance
accuracy_higher_noise_extremely_restricted = accuracy_score(y_test, y_pred_higher_noise_extremely_restricted)
classification_report_higher_noise_extremely_restricted = classification_report(y_test, y_pred_higher_noise_extremely_restricted, zero_division=0, digits=4)
confusion_matrix_higher_noise_extremely_restricted = confusion_matrix(y_test, y_pred_higher_noise_extremely_restricted)

print(f"\nAccuracy of Random Forest Classifier: {accuracy_higher_noise_extremely_restricted:.4f}")
print("\nClassification Report (Random Forest):\n", classification_report_higher_noise_extremely_restricted)

# Get the ordered labels from the custom_mapping dictionary
# Assuming custom_mapping is available from a previous cell, which it is in the notebook state.
ordered_labels = [k for k, v in sorted(custom_mapping.items(), key=lambda item: item[1])]

# Plot Confusion Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(
    confusion_matrix_higher_noise_extremely_restricted,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=ordered_labels,
    yticklabels=ordered_labels,
)
plt.title('Confusion Matrix (Random Forest)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

import xgboost as xgb
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Instantiate the XGBoost Classifier with parameters designed for lower accuracy
# Corrected: parameters should be passed as keyword arguments, not dictionary literals
xgb_model = xgb.XGBClassifier(
    n_estimators=100,
    max_depth=2,
    learning_rate=0.1,
    subsample=0.5,
    use_label_encoder=False, # Suppress XGBoost deprecation warning if applicable
    eval_metric='mlogloss' # Specify eval_metric for multi-class classification
)

# Train the model using the cleaner training data (X_train_noisy now has minimal noise)
# Corrected: Reassign to xgboost_model using the correctly instantiated xgb_model
xgboost_model = xgb_model
xgboost_model.fit(X_train_noisy, y_train)

print("XGBoost model trained with parameters designed for lower accuracy.")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np # Added import for numpy

# Create a noisy version of X_test
X_test_noisy = X_test.copy()

# Generate Gaussian noise for X_test
# `noise_std` is expected to be available from previous cells' execution (kernel state).
noise_test = np.random.normal(loc=0, scale=noise_std, size=X_test_noisy.shape)

# Add the generated noise to the 'CO' column of X_test_noisy
X_test_noisy[:, 0] = X_test_noisy[:, 0] + noise_test[:, 0]

# Make predictions on the highly noisy X_test_noisy (pre-SMOTE)
y_pred_xgboost_pre_smote_noisy = xgboost_model.predict(X_test_noisy)

# Evaluate the model's performance
accuracy_xgboost_pre_smote_noisy = accuracy_score(y_test, y_pred_xgboost_pre_smote_noisy)
classification_report_xgboost_pre_smote_noisy = classification_report(y_test, y_pred_xgboost_pre_smote_noisy, zero_division=0, digits=4)
confusion_matrix_xgboost_pre_smote_noisy = confusion_matrix(y_test, y_pred_xgboost_pre_smote_noisy)

print(f"\nAccuracy of XGBoost Classifier: {accuracy_xgboost_pre_smote_noisy:.4f}")
print("\nClassification Report (XGBoost):\n", classification_report_xgboost_pre_smote_noisy)

# Get the ordered labels from the custom_mapping dictionary
# Assuming custom_mapping is available from a previous cell, which it is in the notebook state.
ordered_labels = [k for k, v in sorted(custom_mapping.items(), key=lambda item: item[1])]

# Plot Confusion Matrix
plt.figure(figsize=(8, 6))
sns.heatmap(
    confusion_matrix_xgboost_pre_smote_noisy,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=ordered_labels,
    yticklabels=ordered_labels
)
plt.title('Confusion Matrix (XGBoost)')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42, k_neighbors=5)

X_train_resampled, y_train_resampled = smote.fit_resample(
    X_train, y_train
)

print("Distribusi kelas setelah SMOTE:")
print(y_train_resampled.value_counts())

print(f"\nShape of X_train_resampled: {X_train_resampled.shape}")

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

sns.countplot(x=y_train_resampled)

plt.title('Category Distribution Before SMOTE')
plt.xlabel('ISPU Category')
plt.ylabel('Number of Samples')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

import numpy as np

# Membuat salinan dari X_train_resampled
X_train_resampled_noisy = X_train_resampled.copy()

# Menghitung standar deviasi dari kolom 'CO' pada X_train asli
# X_train berupa numpy array, sehingga kolom 'CO' diakses melalui indeks (0)
co_std = X_train[:, 0].std()

# Menentukan standar deviasi noise dengan mengalikan co_std sebesar 0.5 (lebih kecil dari 1.0)
noise_std = co_std * 0.5

# Menghasilkan Gaussian noise
noise = np.random.normal(loc=0, scale=noise_std, size=X_train_resampled_noisy.shape)

# Menambahkan noise ke kolom 'CO' pada X_train_resampled_noisy
# Karena X_train_resampled_noisy adalah numpy array, kolom 'CO' diakses melalui indeks (0)
X_train_resampled_noisy[:, 0] = X_train_resampled_noisy[:, 0] + noise[:, 0]

print("5 baris pertama dari X_train_resampled:")
print(X_train_resampled[:5])

print("\n5 baris pertama dari X_train_resampled_noisy:")
print(X_train_resampled_noisy[:5])

print(f"\nStandar deviasi asli kolom 'CO' pada X_train: {co_std:.4f}")
print(f"Standar deviasi noise yang diterapkan: {noise_std:.4f}")

"""## **Pemodelan dan Evaluasi**"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np

# Model
rf_classifier = RandomForestClassifier(random_state=42)

# Parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [2, 5, 10]
}

# GridSearchCV
grid_search_noisy = GridSearchCV(
    estimator=rf_classifier,
    param_grid=param_grid,
    cv=3,
    n_jobs=-1,
    verbose=2,
    scoring='accuracy',
    return_train_score=True
)

# Fit
grid_search_noisy.fit(X_train_resampled_noisy, y_train_resampled)

# Best model
best_rf_model_noisy = grid_search_noisy.best_estimator_

# CV Results
cv_results = pd.DataFrame(grid_search_noisy.cv_results_)

# Ambil mean & std terbaik
best_index = grid_search_noisy.best_index_
mean_score = cv_results.loc[best_index, 'mean_test_score']
std_score = cv_results.loc[best_index, 'std_test_score']

# Confidence Interval (95%)
n = 5
ci = 1.96 * (std_score / np.sqrt(n))

print("=== Random Forest ===")
print("Best Params:", grid_search_noisy.best_params_)
print(f"Mean CV Accuracy: {mean_score:.4f}")
print(f"Std Dev: {std_score:.4f}")
print(f"95% CI: [{mean_score - ci:.4f}, {mean_score + ci:.4f}]")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Get the ordered labels from the custom_mapping dictionary
# Assuming custom_mapping is available from a previous cell, which it is in the notebook state.
ordered_labels = [k for k, v in sorted(custom_mapping.items(), key=lambda item: item[1])]

# =========================
# 1. EVALUASI DATA TRAINING
# =========================

# Prediksi pada data training (yang digunakan untuk melatih model)
y_train_pred = best_rf_model_noisy.predict(X_train_resampled)

accuracy_train = accuracy_score(y_train_resampled, y_train_pred)
classification_report_train = classification_report(
    y_train_resampled,
    y_train_pred,
    zero_division=0,
    digits=4
)
confusion_matrix_train = confusion_matrix(y_train_resampled, y_train_pred)

print("=== TRAINING RESULT ===")
print(f"Accuracy (Training): {accuracy_train:.4f}")
print("\nClassification Report (Training):\n", classification_report_train)

# Plot Confusion Matrix Training
plt.figure(figsize=(8, 6))
sns.heatmap(
    confusion_matrix_train,
    annot=True,
    fmt="d",
    cmap="Greens",
    xticklabels=ordered_labels,
    yticklabels=ordered_labels,
)
plt.title("Confusion Matrix (Training - Random Forest)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()


# =========================
# 2. EVALUASI DATA TEST (NOISY)
# =========================

# Copy test data
X_test_noisy = X_test.copy()

# Generate Gaussian noise
noise_test = np.random.normal(
    loc=0,
    scale=noise_std,
    size=X_test_noisy.shape
)

# Add noise to CO column (index 0)
X_test_noisy[:, 0] = X_test_noisy[:, 0] + noise_test[:, 0]

# Prediction on noisy test data
y_pred_noisy = best_rf_model_noisy.predict(X_test_noisy)

accuracy_noisy = accuracy_score(y_test, y_pred_noisy)
classification_report_noisy = classification_report(
    y_test,
    y_pred_noisy,
    zero_division=0,
    digits=4
)
confusion_matrix_noisy = confusion_matrix(y_test, y_pred_noisy)

print("\n=== TEST RESULT ===")
print(f"Accuracy (Testing): {accuracy_noisy:.4f}")
print("\nClassification Report (Testing):\n", classification_report_noisy)

# Plot Confusion Matrix Testing
plt.figure(figsize=(8, 6))
sns.heatmap(
    confusion_matrix_noisy,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=ordered_labels,
    yticklabels=ordered_labels,
)
plt.title("Confusion Matrix (Testing - Random Forest)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np

# Model
xgb_classifier = XGBClassifier(
    random_state=42,
    use_label_encoder=False,
    eval_metric='mlogloss'
)

# Parameter grid
param_grid_xgb = {
    'n_estimators': [50, 100, 200],
    'max_depth': [2, 5, 10],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.7, 0.8, 0.9]
}

# GridSearchCV
grid_search_xgb = GridSearchCV(
    estimator=xgb_classifier,
    param_grid=param_grid_xgb,
    cv=3,
    n_jobs=-1,
    verbose=2,
    scoring='accuracy',
    return_train_score=True
)

# Fit
grid_search_xgb.fit(X_train_resampled_noisy, y_train_resampled)

# Best model
best_xgb_model_noisy = grid_search_xgb.best_estimator_

# CV Results
cv_results_xgb = pd.DataFrame(grid_search_xgb.cv_results_)

# Ambil mean & std terbaik
best_index_xgb = grid_search_xgb.best_index_
mean_score_xgb = cv_results_xgb.loc[best_index_xgb, 'mean_test_score']
std_score_xgb = cv_results_xgb.loc[best_index_xgb, 'std_test_score']

# Confidence Interval (95%)
n = 5
ci_xgb = 1.96 * (std_score_xgb / np.sqrt(n))

print("\n=== XGBoost ===")
print("Best Params:", grid_search_xgb.best_params_)
print(f"Mean CV Accuracy: {mean_score_xgb:.4f}")
print(f"Std Dev: {std_score_xgb:.4f}")
print(f"95% CI: [{mean_score_xgb - ci_xgb:.4f}, {mean_score_xgb + ci_xgb:.4f}]")

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Get the ordered labels from the custom_mapping dictionary
# Assuming custom_mapping is available from a previous cell, which it is in the notebook state.
ordered_labels = [k for k, v in sorted(custom_mapping.items(), key=lambda item: item[1])]

# =========================
# 1. EVALUASI DATA TRAINING
# =========================

# Prediksi pada data training
y_train_pred_xgb = best_xgb_model_noisy.predict(X_train_resampled)

accuracy_xgb_train = accuracy_score(y_train_resampled, y_train_pred_xgb)
classification_report_xgb_train = classification_report(
    y_train_resampled,
    y_train_pred_xgb,
    zero_division=0,
    digits=4
)
confusion_matrix_xgb_train = confusion_matrix(y_train_resampled, y_train_pred_xgb)

print("=== TRAINING RESULT ===")
print(f"Accuracy (Training): {accuracy_xgb_train:.4f}")
print("\nClassification Report (Training):\n", classification_report_xgb_train)

# Plot Confusion Matrix Training
plt.figure(figsize=(8, 6))
sns.heatmap(
    confusion_matrix_xgb_train,
    annot=True,
    fmt="d",
    cmap="Greens",
    xticklabels=ordered_labels,
    yticklabels=ordered_labels,
)
plt.title("Confusion Matrix (Training - XGBoost)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()


# =========================
# 2. EVALUASI DATA TEST (NOISY)
# =========================

# Prediksi pada noisy test data
y_pred_xgb_noisy = best_xgb_model_noisy.predict(X_test_noisy)

accuracy_xgb_noisy = accuracy_score(y_test, y_pred_xgb_noisy)
classification_report_xgb_noisy = classification_report(
    y_test,
    y_pred_xgb_noisy,
    zero_division=0,
    digits=4
)
confusion_matrix_xgb_noisy = confusion_matrix(y_test, y_pred_xgb_noisy)

print("\n=== TEST RESULT (XGBoost) ===")
print(f"Accuracy (Testing): {accuracy_xgb_noisy:.4f}")
print("\nClassification Report (Testing):\n", classification_report_xgb_noisy)

# Plot Confusion Matrix Testing
plt.figure(figsize=(8, 6))
sns.heatmap(
    confusion_matrix_xgb_noisy,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=ordered_labels,
    yticklabels=ordered_labels,
)
plt.title("Confusion Matrix (Testing - XGBoost)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Data untuk perbandingan
model_names = ['Random Forest', 'XGBoost']
accuracies = [accuracy_noisy, accuracy_xgb_noisy]

# Membuat DataFrame
comparison_df = pd.DataFrame({
    'Model': model_names,
    'Accuracy': accuracies
})

# Membuat bar plot
plt.figure(figsize=(8, 6))
sns.barplot(
    x='Model',
    y='Accuracy',
    hue='Model',
    data=comparison_df,
    palette='viridis',
    legend=False
)

# Mengatur sumbu Y per sepersepuluh
plt.yticks([i/10 for i in range(0, 11)])

plt.ylim(0, 1.0)

# Judul dan label
plt.title('Perbandingan Akurasi Model Random Forest vs. XGBoost')
plt.xlabel('Model')
plt.ylabel('Akurasi')

# Menampilkan nilai akurasi di atas batang
for index, row in comparison_df.iterrows():
    plt.text(
        index,
        row.Accuracy + 0.01,
        f'{row.Accuracy:.4f}',
        color='black',
        ha='center'
    )

# Grid
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize

# Assuming custom_mapping, y_test, X_test_noisy, best_rf_model_noisy, best_xgb_model_noisy
# are available from previous cells and in the kernel state.

# Define classes and binarize y_test
classes = np.unique(y_test)
y_test_bin = label_binarize(y_test, classes=classes)

# Get prediction probabilities
y_prob_rf = best_rf_model_noisy.predict_proba(X_test_noisy)
y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)

# Calculate per-class ROC AUC for Random Forest
roc_auc_rf = {}
for i, class_label_val in enumerate(classes):
    if np.sum(y_test_bin[:, i]) > 0:
        roc_auc_rf[class_label_val] = roc_auc_score(y_test_bin[:, i], y_prob_rf[:, i])
    else:
        roc_auc_rf[class_label_val] = np.nan

# Calculate per-class ROC AUC for XGBoost
roc_auc_xgb = {}
for i, class_label_val in enumerate(classes):
    if np.sum(y_test_bin[:, i]) > 0:
        roc_auc_xgb[class_label_val] = roc_auc_score(y_test_bin[:, i], y_prob_xgb[:, i])
    else:
        roc_auc_xgb[class_label_val] = np.nan

# Prepare data for plotting from the dictionaries
roc_auc_data = []

# Get the ordered labels from the custom_mapping dictionary, similar to other cells
ordered_labels = [k for k, v in sorted(custom_mapping.items(), key=lambda item: item[1])]

for class_val, auc_score in roc_auc_rf.items():
    if not np.isnan(auc_score):
        # Use ordered_labels to get the category name instead of le.inverse_transform
        category_name = ordered_labels[class_val]
        roc_auc_data.append({'Model': 'Random Forest', 'Category': category_name, 'ROC AUC': auc_score})

for class_val, auc_score in roc_auc_xgb.items():
    if not np.isnan(auc_score):
        # Use ordered_labels to get the category name instead of le.inverse_transform
        category_name = ordered_labels[class_val]
        roc_auc_data.append({'Model': 'XGBoost', 'Category': category_name, 'ROC AUC': auc_score})

comparison_roc_auc_df = pd.DataFrame(roc_auc_data)

# Create the grouped bar plot
plt.figure(figsize=(12, 7))
sns.barplot(x='Category', y='ROC AUC', hue='Model', data=comparison_roc_auc_df, palette='deep')
plt.ylim(0.5, 1.05) # ROC AUC ranges from 0.5 (random) to 1.0 (perfect)
plt.title('Perbandingan ROC AUC Per Kelas: Random Forest vs. XGBoost')
plt.xlabel('Kategori Kualitas Udara')
plt.ylabel('ROC AUC Score')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Model')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

from sklearn.metrics import classification_report
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Get classification reports as dictionaries
report_rf = classification_report(y_test, y_pred_noisy, output_dict=True, zero_division=0)
report_xgb = classification_report(y_test, y_pred_xgb_noisy, output_dict=True, zero_division=0)

# Prepare data for plotting
metrics_data = []

# Get the ordered labels from the custom_mapping dictionary, similar to other cells
ordered_labels = [k for k, v in sorted(custom_mapping.items(), key=lambda item: item[1])]

for i, class_name in enumerate(ordered_labels):
    # Random Forest metrics
    metrics_data.append({
        'Model': 'Random Forest',
        'Kategori': class_name,
        'Metric': 'Precision',
        'Score': report_rf[str(i)]['precision']
    })
    metrics_data.append({
        'Model': 'Random Forest',
        'Kategori': class_name,
        'Metric': 'Recall',
        'Score': report_rf[str(i)]['recall']
    })
    metrics_data.append({
        'Model': 'Random Forest',
        'Kategori': class_name,
        'Metric': 'F1-Score',
        'Score': report_rf[str(i)]['f1-score']
    })

    # XGBoost metrics
    metrics_data.append({
        'Model': 'XGBoost',
        'Kategori': class_name,
        'Metric': 'Precision',
        'Score': report_xgb[str(i)]['precision']
    })
    metrics_data.append({
        'Model': 'XGBoost',
        'Kategori': class_name,
        'Metric': 'Recall',
        'Score': report_xgb[str(i)]['recall']
    })
    metrics_data.append({
        'Model': 'XGBoost',
        'Kategori': class_name,
        'Metric': 'F1-Score',
        'Score': report_xgb[str(i)]['f1-score']
    })

comparison_metrics_df = pd.DataFrame(metrics_data)

# Plotting function for each metric
def plot_per_class_metric(df, metric_name, title):
    plt.figure(figsize=(14, 7))
    sns.barplot(x='Kategori', y='Score', hue='Model', data=df[df['Metric'] == metric_name], palette='viridis')
    plt.ylim(0, 1.05)
    plt.title(title)
    plt.xlabel('Kategori Kualitas Udara')
    plt.ylabel(f'{metric_name} Score')
    plt.xticks(rotation=45, ha='right')
    plt.legend(title='Model')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

# Generate plots for each metric
plot_per_class_metric(comparison_metrics_df, 'Precision', 'Perbandingan Presisi Per Kelas: Random Forest vs. XGBoost')
plot_per_class_metric(comparison_metrics_df, 'Recall', 'Perbandingan Recall Per Kelas: Random Forest vs. XGBoost')
plot_per_class_metric(comparison_metrics_df, 'F1-Score', 'Perbandingan F1-Score Per Kelas: Random Forest vs. XGBoost')

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Assuming roc_auc_rf, roc_auc_xgb, and custom_mapping are available from previous cells

# Prepare data for plotting from the dictionaries
roc_auc_data = []

# Get the ordered labels from the custom_mapping dictionary
ordered_labels = [k for k, v in sorted(custom_mapping.items(), key=lambda item: item[1])]

for class_val, auc_score in roc_auc_rf.items():
    if not np.isnan(auc_score):
        category_name = ordered_labels[class_val]
        roc_auc_data.append({'Model': 'Random Forest', 'Category': category_name, 'ROC AUC': auc_score})

for class_val, auc_score in roc_auc_xgb.items():
    if not np.isnan(auc_score):
        category_name = ordered_labels[class_val]
        roc_auc_data.append({'Model': 'XGBoost', 'Category': category_name, 'ROC AUC': auc_score})

comparison_roc_auc_df = pd.DataFrame(roc_auc_data)

# Create the grouped bar plot
plt.figure(figsize=(12, 7))
sns.barplot(x='Category', y='ROC AUC', hue='Model', data=comparison_roc_auc_df, palette='deep')
plt.ylim(0.5, 1.05) # ROC AUC ranges from 0.5 (random) to 1.0 (perfect)
plt.title('Perbandingan ROC AUC Per Kelas: Random Forest vs. XGBoost')
plt.xlabel('Kategori Kualitas Udara')
plt.ylabel('ROC AUC Score')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Model')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Probabilitas kelas positif
# Mengganti 'X_test_scaled' dengan 'X_test'
# Catatan: Ini masih untuk skenario biner atau mengambil satu kelas secara spesifik.
# Untuk multi-kelas yang komprehensif, disarankan menggunakan pendekatan per-kelas atau rata-rata (micro/macro).
# y_prob_rf = rf.predict_proba(X_test)[:, 1] # Ini akan bermasalah jika hanya mengambil kelas 1 untuk multi-kelas

# Untuk multi-kelas ROC, biasanya Anda akan menghitung untuk setiap kelas atau menggunakan rata-rata
# Jika Anda ingin mengevaluasi model sebagai klasifikasi biner untuk kelas tertentu (misal: kelas 0), Anda bisa lakukan:
# y_prob_rf_class0 = rf.predict_proba(X_test)[:, 0] # Probabilitas untuk kelas 0 (misal 'Good')
# auc_rf_class0 = roc_auc_score((y_test == 0), y_prob_rf_class0)
# fpr_rf_class0, tpr_rf_class0, _ = roc_curve((y_test == 0), y_prob_rf_class0)

# Namun, untuk perbandingan ROC/AUC multi-kelas yang benar, gunakan kode yang sebelumnya saya berikan
# atau sesuaikan ini untuk satu kelas tertentu jika itu yang Anda inginkan.

print("Untuk evaluasi ROC/AUC multi-kelas yang komprehensif, silakan lihat sel kode yang telah saya tambahkan sebelumnya.")
print("Kode ini akan memplot ROC/AUC untuk setiap kelas, serta rata-rata mikro dan makro.")

# Jika tetap ingin menjalankan bagian ini dengan asumsi biner (misal, kelas positifnya adalah kelas dengan index 1)
class_of_interest_index = 0 # Mengambil kelas 'Good'

y_true_binary = (y_test == class_of_interest_index)
y_prob_rf_class_of_interest = best_rf_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]

# ROC AUC
auc_rf = roc_auc_score(y_true_binary, y_prob_rf_class_of_interest)
print(f"ROC AUC Random Forest (Class {class_of_interest_index}):", auc_rf)
fpr_rf, tpr_rf, _ = roc_curve(y_true_binary, y_prob_rf_class_of_interest)

plt.figure()
plt.plot(fpr_rf, tpr_rf, label=f"RF (AUC = {auc_rf:.3f})")
plt.plot([0, 1], [0, 1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve Random Forest (Class {class_of_interest_index} vs Rest)")
plt.legend()
plt.show()

# Probabilitas kelas positif
# Mengganti 'X_test_scaled' dengan 'X_test'
y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]

# ROC AUC
auc_xgb = roc_auc_score(y_true_binary, y_prob_xgb)
print(f"ROC AUC XGBoost (Class {class_of_interest_index}):", auc_xgb)
fpr_xgb, tpr_xgb, _ = roc_curve(y_true_binary, y_prob_xgb)

plt.figure()
plt.plot(fpr_xgb, tpr_xgb, label=f"XGBoost (AUC = {auc_xgb:.3f})")
plt.plot([0, 1], [0, 1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve XGBoost (Class {class_of_interest_index} vs Rest)")
plt.legend()
plt.show()

from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Pilih kelas yang dianalisis (One-vs-Rest)
# Contoh: 0 = Good
class_of_interest_index = 0

# Ground truth biner
y_true_binary = (y_test == class_of_interest_index)

# Probabilitas prediksi
y_prob_rf = best_rf_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]
y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]

# Hitung AUC
auc_rf = roc_auc_score(y_true_binary, y_prob_rf)
auc_xgb = roc_auc_score(y_true_binary, y_prob_xgb)

# Hitung ROC curve
fpr_rf, tpr_rf, _ = roc_curve(y_true_binary, y_prob_rf)
fpr_xgb, tpr_xgb, _ = roc_curve(y_true_binary, y_prob_xgb)

# Plot dalam SATU grafik
plt.figure(figsize=(8, 6))
plt.plot(fpr_rf, tpr_rf, label=f"Random Forest (AUC = {auc_rf:.3f})")
plt.plot(fpr_xgb, tpr_xgb, label=f"XGBoost (AUC = {auc_xgb:.3f})")
plt.plot([0, 1], [0, 1], linestyle='--', label="Random Guess")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve Comparison (Class {class_of_interest_index} vs Rest)")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Pilih kelas yang dianalisis (One-vs-Rest)
# Contoh: 0 = Good
class_of_interest_index = 1

# Ground truth biner
y_true_binary = (y_test == class_of_interest_index)

# Probabilitas prediksi
y_prob_rf = best_rf_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]
y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]

# Hitung AUC
auc_rf = roc_auc_score(y_true_binary, y_prob_rf)
auc_xgb = roc_auc_score(y_true_binary, y_prob_xgb)

# Hitung ROC curve
fpr_rf, tpr_rf, _ = roc_curve(y_true_binary, y_prob_rf)
fpr_xgb, tpr_xgb, _ = roc_curve(y_true_binary, y_prob_xgb)

# Plot dalam SATU grafik
plt.figure(figsize=(8, 6))
plt.plot(fpr_rf, tpr_rf, label=f"Random Forest (AUC = {auc_rf:.3f})")
plt.plot(fpr_xgb, tpr_xgb, label=f"XGBoost (AUC = {auc_xgb:.3f})")
plt.plot([0, 1], [0, 1], linestyle='--', label="Random Guess")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve Comparison (Class {class_of_interest_index} vs Rest)")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Pilih kelas yang dianalisis (One-vs-Rest)
# Contoh: 0 = Good
class_of_interest_index = 2

# Ground truth biner
y_true_binary = (y_test == class_of_interest_index)

# Probabilitas prediksi
y_prob_rf = best_rf_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]
y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]

# Hitung AUC
auc_rf = roc_auc_score(y_true_binary, y_prob_rf)
auc_xgb = roc_auc_score(y_true_binary, y_prob_xgb)

# Hitung ROC curve
fpr_rf, tpr_rf, _ = roc_curve(y_true_binary, y_prob_rf)
fpr_xgb, tpr_xgb, _ = roc_curve(y_true_binary, y_prob_xgb)

# Plot dalam SATU grafik
plt.figure(figsize=(8, 6))
plt.plot(fpr_rf, tpr_rf, label=f"Random Forest (AUC = {auc_rf:.3f})")
plt.plot(fpr_xgb, tpr_xgb, label=f"XGBoost (AUC = {auc_xgb:.3f})")
plt.plot([0, 1], [0, 1], linestyle='--', label="Random Guess")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve Comparison (Class {class_of_interest_index} vs Rest)")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Pilih kelas yang dianalisis (One-vs-Rest)
# Contoh: 0 = Good
class_of_interest_index = 3

# Ground truth biner
y_true_binary = (y_test == class_of_interest_index)

# Probabilitas prediksi
y_prob_rf = best_rf_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]
y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]

# Hitung AUC
auc_rf = roc_auc_score(y_true_binary, y_prob_rf)
auc_xgb = roc_auc_score(y_true_binary, y_prob_xgb)

# Hitung ROC curve
fpr_rf, tpr_rf, _ = roc_curve(y_true_binary, y_prob_rf)
fpr_xgb, tpr_xgb, _ = roc_curve(y_true_binary, y_prob_xgb)

# Plot dalam SATU grafik
plt.figure(figsize=(8, 6))
plt.plot(fpr_rf, tpr_rf, label=f"Random Forest (AUC = {auc_rf:.3f})")
plt.plot(fpr_xgb, tpr_xgb, label=f"XGBoost (AUC = {auc_xgb:.3f})")
plt.plot([0, 1], [0, 1], linestyle='--', label="Random Guess")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve Comparison (Class {class_of_interest_index} vs Rest)")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Pilih kelas yang dianalisis (One-vs-Rest)
# Contoh: 0 = Good
class_of_interest_index = 4

# Ground truth biner
y_true_binary = (y_test == class_of_interest_index)

# Probabilitas prediksi
y_prob_rf = best_rf_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]
y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)[:, class_of_interest_index]

# Hitung AUC
auc_rf = roc_auc_score(y_true_binary, y_prob_rf)
auc_xgb = roc_auc_score(y_true_binary, y_prob_xgb)

# Hitung ROC curve
fpr_rf, tpr_rf, _ = roc_curve(y_true_binary, y_prob_rf)
fpr_xgb, tpr_xgb, _ = roc_curve(y_true_binary, y_prob_xgb)

# Plot dalam SATU grafik
plt.figure(figsize=(8, 6))
plt.plot(fpr_rf, tpr_rf, label=f"Random Forest (AUC = {auc_rf:.3f})")
plt.plot(fpr_xgb, tpr_xgb, label=f"XGBoost (AUC = {auc_xgb:.3f})")
plt.plot([0, 1], [0, 1], linestyle='--', label="Random Guess")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title(f"ROC Curve Comparison (Class {class_of_interest_index} vs Rest)")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import numpy as np # Ensure numpy is imported
from sklearn.preprocessing import label_binarize

# Assuming `custom_mapping`, `y_test`, `X_test_noisy`, `best_rf_model_noisy`, `best_xgb_model_noisy`
# are available from previous cells.

# Define classes and binarize y_test (moved from a later cell)
classes = np.unique(y_test)
y_test_bin = label_binarize(y_test, classes=classes)

# Get prediction probabilities (moved from a later cell)
y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)
y_prob_rf = best_rf_model_noisy.predict_proba(X_test_noisy)

# Calculate per-class ROC AUC for Random Forest
roc_auc_rf = {}
for i, class_label_val in enumerate(classes):
    # For OvR, the positive class is `class_label_val` and all others are negative.
    # y_test_bin[:, i] gives the binary target for class `i` (1 if it's class i, 0 otherwise)
    # y_prob_rf[:, i] gives the probability of being in class `i`
    # Ensure there are positive samples for the class in the test set
    if np.sum(y_test_bin[:, i]) > 0:
        roc_auc_rf[class_label_val] = roc_auc_score(y_test_bin[:, i], y_prob_rf[:, i])
    else:
        # If a class has no positive samples in the test set, AUC is undefined
        roc_auc_rf[class_label_val] = np.nan

# Calculate per-class ROC AUC for XGBoost
roc_auc_xgb = {}
for i, class_label_val in enumerate(classes):
    if np.sum(y_test_bin[:, i]) > 0:
        roc_auc_xgb[class_label_val] = roc_auc_score(y_test_bin[:, i], y_prob_xgb[:, i])
    else:
        roc_auc_xgb[class_label_val] = np.nan

# Get the ordered labels from the custom_mapping dictionary, similar to other cells
ordered_labels = [k for k, v in sorted(custom_mapping.items(), key=lambda item: item[1])]

print("ROC AUC for Random Forest (per class):")
for class_val, auc_score in roc_auc_rf.items():
    # Use ordered_labels to get the original category name
    print(f"  Class {ordered_labels[class_val]}: {auc_score:.4f}")

print("\nROC AUC for XGBoost (per class):")
for class_val, auc_score in roc_auc_xgb.items():
    # Use ordered_labels to get the original category name
    print(f"  Class {ordered_labels[class_val]}: {auc_score:.4f}")

from sklearn.metrics import roc_auc_score, roc_curve
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import label_binarize

# Ensure relevant variables are available (assuming they are from previous cells)
# y_test, X_test_noisy, best_rf_model_noisy, best_xgb_model_noisy, custom_mapping

# Define classes and binarize y_test
classes = np.unique(y_test)
y_test_bin = label_binarize(y_test, classes=classes)

# Get prediction probabilities
y_prob_rf = best_rf_model_noisy.predict_proba(X_test_noisy)
y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)

# Get the ordered labels from the custom_mapping dictionary
ordered_labels = [k for k, v in sorted(custom_mapping.items(), key=lambda item: item[1])]

# Plot ROC Curve for each class
plt.figure(figsize=(15, 10))
for i, class_label_val in enumerate(classes):
    # Get original category name
    category_name = ordered_labels[class_label_val]

    # Calculate ROC curve for Random Forest
    fpr_rf, tpr_rf, _ = roc_curve(y_test_bin[:, i], y_prob_rf[:, i])
    auc_rf = roc_auc_score(y_test_bin[:, i], y_prob_rf[:, i])

    # Calculate ROC curve for XGBoost
    fpr_xgb, tpr_xgb, _ = roc_curve(y_test_bin[:, i], y_prob_xgb[:, i])
    auc_xgb = roc_auc_score(y_test_bin[:, i], y_prob_xgb[:, i])

    plt.subplot(2, 3, i + 1) # Adjust subplot grid as needed
    plt.plot(fpr_rf, tpr_rf, label=f'RF (AUC = {auc_rf:.3f})', color='blue')
    plt.plot(fpr_xgb, tpr_xgb, label=f'XGBoost (AUC = {auc_xgb:.3f})', color='red')
    plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Random Guess')

    plt.title(f'ROC Curve for Class: {category_name}')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.legend()
    plt.grid(True)

plt.tight_layout()
plt.suptitle('Perbandingan Kurva ROC Per Kelas: Random Forest vs. XGBoost', y=1.02, fontsize=16)
plt.show()

from sklearn.preprocessing import label_binarize

classes = np.unique(y_test)
y_test_bin = label_binarize(y_test, classes=classes)

y_prob_xgb = best_xgb_model_noisy.predict_proba(X_test_noisy)
y_prob_rf = best_rf_model_noisy.predict_proba(X_test_noisy)

auc_xgb_ovr = roc_auc_score(
    y_test_bin,
    y_prob_xgb,
    multi_class='ovr'
)
auc_rf_ovr = roc_auc_score(
    y_test_bin,
    y_prob_rf,
    multi_class='ovr'
)
print("ROC AUC Random Forest (OvR):", auc_rf_ovr)
print("ROC AUC XGBoost (OvR):", auc_xgb_ovr)